services:
  - type: web
    name: tugyi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && pip install wgcf"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
